{{
    config(
        materialized = 'incremental',
        unique_key   = 'order_key',
        incremental_strategy = 'merge'
    )
}}

-- Silver: expand the nested payload into columns, cast, and collapse
-- at-least-once duplicates to one row per order. The body is generated by
-- build_silver_stream from seeds/config/ -- see docs/streams.md.
--
-- Not a dynamic table: the QUALIFY makes Snowflake report
-- refresh_mode = FULL ("complex query"), because a window function's
-- ranking can be altered by any new row, so it rebuilds instead of
-- maintaining a delta. An incremental model issues an explicit MERGE and
-- carries no such penalty -- at the cost of needing something to schedule
-- it (snowflake/04_dbt_project.sql).

-- Declared here because dbt builds the DAG at parse time, before the config
-- tables can be read.
-- depends_on: {{ ref('stream_config') }}
-- depends_on: {{ ref('stream_column_config') }}
-- depends_on: {{ ref('bronze_orders') }}

{{ build_silver_stream('orders') }}
