#!/usr/bin/env bash
# Resolve a named profile/target, render the connector config, and POST it
# to the Connect worker. Re-running updates the connector in place.
#
#   ./scripts/deploy_connector.sh
#   ./scripts/deploy_connector.sh --target prod
#   ./scripts/deploy_connector.sh --profile tpch_stream --target dev
#   CONNECTOR_PROFILES_PATH=~/.dbt/profiles.yml ./scripts/deploy_connector.sh --profile tpch_pipeline
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Optional: holds the profile/target selector and CONNECT_URL only.
if [[ -f .env ]]; then set -a; source .env; set +a; fi

# PyYAML ships with dbt, so the project venv already has it.
PY="$ROOT/../.venv/bin/python"
[[ -x "$PY" ]] || PY="$(command -v python3)"

eval "$("$PY" scripts/resolve_profile.py "$@" | sed 's/^/export /')"

echo "profile : $RESOLVED_PROFILE"
echo "target  : $RESOLVED_TARGET"
echo "source  : $RESOLVED_PROFILES_PATH"
echo "snowflake: $SNOWFLAKE_USER@$SNOWFLAKE_ACCOUNT as $SNOWFLAKE_ROLE -> $SNOWFLAKE_DATABASE.$SNOWFLAKE_SCHEMA"
echo

if grep -qi ENCRYPTED "$SNOWFLAKE_PRIVATE_KEY_PATH"; then
  echo "Key is encrypted; add snowflake.private.key.passphrase to the template." >&2
  exit 1
fi

# Write the key into the properties file the worker's FileConfigProvider
# reads. This keeps it OUT of the connector config: Connect persists configs
# to the _connect_configs topic and echoes them back over the REST API, so an
# inlined key would sit in plaintext in both.
mkdir -p secrets && chmod 700 secrets
KEY_PROPS="secrets/snowflake.properties"
umask 077
{
  echo "# Generated by deploy_connector.sh -- do not commit."
  printf 'snowflake_private_key=%s\n' \
    "$(grep -v -- '-----' "$SNOWFLAKE_PRIVATE_KEY_PATH" | tr -d '\n')"
} > "$KEY_PROPS"
echo "Wrote $KEY_PROPS (mounted read-only into the connect container)."

# Which topics this ONE connector subscribes to, and where each lands. Both
# lists must agree: a topic with no mapping does not error, the connector
# derives a table name from the topic and lands rows nobody is reading.
#
# Adding a stream is an edit here (or in .env), not a second connector.
export KAFKA_TOPICS="${KAFKA_TOPICS:-orders,payments}"
export KAFKA_TOPIC_TABLE_MAP="${KAFKA_TOPIC_TABLE_MAP:-orders:ORDERS_STREAM,payments:PAYMENTS_STREAM}"

# One dead-letter topic for every stream: per-topic DLQs multiply the things
# you have to remember to watch.
export KAFKA_DLQ_TOPIC="${KAFKA_DLQ_TOPIC:-dlq.streams}"

CONNECT_URL="${CONNECT_URL:-http://localhost:8083}"
RENDERED="$(mktemp)"; BODY="$(mktemp)"
trap 'rm -f "$RENDERED" "$BODY"' EXIT

"$PY" - "$ROOT/connectors/snowflake-sink.json.template" > "$RENDERED" <<'PY'
import os, re, sys
tpl = open(sys.argv[1]).read()
missing = []
def sub(m):
    k = m.group(1)
    v = os.environ.get(k)
    if v is None:
        missing.append(k)
        return m.group(0)
    return v.replace('\\', '\\\\').replace('"', '\\"')
# \w+ only, so Connect's own ${file:/path:key} references -- which contain
# ':' and '/' -- are left untouched for the worker to resolve.
out = re.sub(r'\$\{(\w+)\}', sub, tpl)
if missing:
    sys.exit("Unset variables: " + ", ".join(sorted(set(missing))))
sys.stdout.write(out)
PY

NAME="$("$PY" -c 'import json,sys; print(json.load(open(sys.argv[1]))["name"])' "$RENDERED")"
"$PY" -c 'import json,sys; json.dump(json.load(open(sys.argv[1]))["config"], open(sys.argv[2],"w"))' \
  "$RENDERED" "$BODY"

echo "Deploying connector '$NAME' to $CONNECT_URL ..."
curl -sS -X PUT \
  -H 'Content-Type: application/json' \
  --data-binary "@$BODY" \
  "$CONNECT_URL/connectors/$NAME/config" >/dev/null

echo "Deployed. Status:"
sleep 3
curl -sS "$CONNECT_URL/connectors/$NAME/status" | "$PY" -m json.tool
