tpch_stream:
  target: dev
  outputs:

    dev:
      account:          ${SNOWFLAKE_ACCOUNT}
      user:             kafka_ingest_svc
      role:             kafka_ingest
      database:         DBT_PIPE

      schema:           RAW_STREAMS
      warehouse:        wh_transform
      private_key_path: ./secrets/kafka_ingest_key.p8

    prod:
      account:          ${SNOWFLAKE_ACCOUNT}
      user:             kafka_ingest_svc
      role:             kafka_ingest
      database:         DBT_PIPE
      schema:           RAW_PROD
      warehouse:        wh_transform
      private_key_path: ./secrets/kafka_ingest_key.p8
